version: "2.3"
services:
  proxy:
    depends_on:
      - app
    restart: "no"

  dns:
    networks:
      main: { }
    restart: "no"

  app:
    image: ealen/echo-server:latest
    networks:
      main: { }
    restart: "no"

networks:
  main:
    driver: bridge
